### PR TITLE
ffi

### PR DESCRIPTION
**Pull request by paf31**
/cc @garyb 

Does this look ok? We might want to include your "FFI tips" article here too.

Thanks.

### CODE REVIEW

**Comment by garyb** [comment]
Can we use h4s for the article section headings rather than h3s? Looks good apart from that :+1: 

I'll have a look at the FFI tips article, is it even still relevant? :smile:

**Comment by garyb** [comment]
Perhaps if I actually finished it it would be good too!

**Comment by paf31** [comment]
> Can we use h4s for the article section headings rather than h3s?

Will do.

> I'll have a look at the FFI tips article, is it even still relevant?

It might need some updating. This article is like a bunch of tips as well though, towards the end, so it might make sense to add your article as a bunch of additional sections?

**Comment by garyb** [comment]
Oh, actually, should we mention about defining things as `exports["example'"]` over `exports.example$prime`?

**Comment by paf31** [comment]
Makes sense. I'll add an issue, since I don't have time to update it right now, but I can look later.

**Comment by garyb** [comment]
Ok, cool. I'll add/update some of the tips along with that if I get around to it before you then.

**Pull request merged**
