### PR TITLE
Re-add link to updated version of PS book

### LINKED ISSUE #143: Re add link to updated PS Book?
Since the book is being updated and we now have the https://book.purescript.org link, should we re-add the book to this website?

### PR DESCRIPTION
**Pull request by JordanMartinez**
Fixes #143 

Funny how I originally removed this a year ago.

### CODE REVIEW

**Comment by hdgarrood** [comment]
What do you think about dropping "currently-being-updated"? It's only chapter 12 which still needs updating, right? I'm just a bit worried that a) we might forget to remove it when the book is fully updated, and b) it will make beginners think it's not worth bothering with, when in reality even reading the first few chapters should set them up pretty well.

**Comment by JordanMartinez** [comment]
Seems reasonable to me! I won't get to this until later tonight if not
tomorrow.

**Comment by JordanMartinez** [comment]
I'm not actually sure whether it's only chapter 12 that needs to be updated. Isn't there something about chapter 8 in need of some refactoring, too?

Regardless, I think your point about not discouraging people from using it is still valid and why that phrase should be dropped. Besides, the book itself tells them that it's being updated anyways.

**Comment by JordanMartinez** [comment]
Also, this PR is ready now. I've removed that phrase.

**Comment by hdgarrood** [comment]
Thanks!

**Pull request merged**
