### PR TITLE
Pull out community section on Learn page

### LINKED ISSUE #50: Add Community section
I think there could be a "Community" page and a link to it in the top navbar. This is pretty common nowadays and would promote interaction and community building.

### PR DESCRIPTION
**Pull request by paf31**
Resolves #50.

### CODE REVIEW

**Comment by damncabbage** [comment]
Would you mind if, as per #50, it did get pulled out to an entirely-separate _"… Community page and a link to it in the top navbar"_?

These language homepages do the same:
* https://www.haskell.org/
* http://elm-lang.org/
* https://ocaml.org/
* https://www.ruby-lang.org/en/
* https://www.python.org/
* http://www.lua.org/
* http://julialang.org/

... And likely others I haven't run across yet.

**Comment by damncabbage** [comment]
(To be clear, I'm happy to do the leg-work on the rearrangement, if I can get a hand with the instructions that need to be run to make Pandoc produce the site.)

**Comment by paf31** [comment]
:+1: Sounds good to me.

**Comment by garyb** [comment]
We'll have to rejig the media queries for the navigation if we add another item I think, but making a separate page is good by me too.

**Comment by damncabbage** [comment]
Thanks. Will have a PR up tomorrow morning AU-EDT.

**Pull request merged**
