### PR TITLE
return should be pure.

### PR DESCRIPTION
**Pull request by mlang**

### CODE REVIEW

**Comment by paf31** [comment]
Can you please rebase and run the `stack exec build` script to build the HTML?

**Comment by mlang** [comment]
`stack exec build` fails for me, complains about not being able to find
"build".

-- 
CYa,
  ⡍⠁⠗⠊⠕ | Blog: <https://blind.guru/>  GitHub: <https://github.com/mlang/>
  .''`. | Twitter: @blindbird23        FaceBook: disyled
 : :' : | SoundCloud: <soundcloud.com/mario-lang>
 `. `'  | YouTube: <youtube.com/user/mlang23>
   `-

**Comment by LiamGoodacre** [comment]
Do you mean: `stack build`, `stack exec site rebuild`? (from README.md)

**Comment by paf31** [comment]
Yes, that, sorry.

**Comment by hdgarrood** [comment]
Fixed by https://github.com/purescript/purescript.github.io/commit/175c8af3ca9f0e9dc71ccf6f79b787e68fb04d22. Thanks for bringing this to our attention!

**Pull request closed without merging**
