### PR TITLE
fix for a bug in the quickcheck article

### PR DESCRIPTION
**Pull request by soupi**
[Snippet in try purescript](http://try.purescript.org/?gist=90b247c05ef52ed0f2fdbac1c6fec6b8&backend=core).

### CODE REVIEW

**Comment by hdgarrood** [comment]
Thanks! Rather that modifying the HTML directly, though, please modify _generator/learn/quickcheck/index.markdown and then rerun the generator as described in the README, so that we don't lose this again next time we modify anything.

**Comment by soupi** [comment]
oh sorry!

**Comment by hdgarrood** [comment]
No worries :) let me know if anything's at all unclear.

**Comment by soupi** [comment]
there we go.

**Comment by hdgarrood** [comment]
Thanks!

**Pull request merged**
