### PR TITLE
Adds Separate "Community" Page

### PR DESCRIPTION
**Pull request by damncabbage**
(See https://github.com/purescript/purescript.github.io/pull/71#issuecomment-195721761 and #50.)

### CODE REVIEW

**Comment by damncabbage** [comment]
Screenshot for quick reference:

screen shot 2016-03-15 at 1 57 10 pm

**Comment by damncabbage** [comment]
**Edit:** "Online Meetups" => "Online"; accidentally left an old title.

**Comment by paf31** [comment]
Looks good to me.

**Comment by damncabbage** [comment]
Who else needs to look this over before it gets a merge-thumbs-up? (Gary B?)

**Comment by paf31** [comment]
@garyb Do you mind having a look?

**Comment by garyb** [comment]
Looks great :+1:

**Comment by paf31** [comment]
Thanks!

**Pull request merged**
