### PR TITLE
Update styles and fix some links for the article page

### PR DESCRIPTION
**Pull request by garyb**
@paf31 I'm pretty happy with this, how about you?

Some minor changes needed to the code for future articles:

- Add an `article` class to the content `section`
- Use `h4` for titles for sections within the article
- Don't indent the generated code as it interferes with the `pre` formatting

I'd like to reinstate a proper blog/article index page once we have a few more things too.

### CODE REVIEW

**Comment by garyb** [comment]
I was thinking too, maybe this article would be better split into two: one just covering the basic pulp stuff, and then break out the Project Euler solving into its own piece?

**Comment by garyb** [comment]
Also, sorry it took me so long to get around to this!

**Comment by paf31** [comment]
I like it, thanks for doing this. Looks nice on the phone too.

I'm happy to break up the content if you think it would help. The Project Euler thing was just a simple example to demonstrate how to write a project and test it though. It might be too simple for its own article?

**Comment by garyb** [comment]
Fair enough!

**Pull request merged**
