### PR TITLE
Add the favicon

### PR DESCRIPTION
**Pull request by hdgarrood**
Adds the favicon which was originally merged in #67 so that it is
actually included in the site.

### CODE REVIEW

**Comment by hdgarrood** [comment]
I've just realised that we haven't properly documented the contributing / building / publishing process. Does anyone remember how it works?

**Comment by hdgarrood** [comment]
Ah: https://github.com/purescript/purescript.github.io/pull/66#issuecomment-195010819 and the following comments.

**Comment by hdgarrood** [comment]
Oh also, we have a directory of PNG images here: https://github.com/purescript/logo/tree/master/images perhaps we should use those instead? /cc @naehrstoff

**Comment by hdgarrood** [comment]
Oh, I just saw https://github.com/purescript/purescript.github.io/commit/9fe3c4786012b6bb4a6bb0e8a41a7c524054e25d. I guess the goal is to use the strategy described in https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch so that we don't need to maintain two branches and we also don't need to do anything when receiving contributions other than making sure the site has been regenerated and the output has been checked in? I think we would need to change the name of this repo for that to work, based on what's written on that help page. That sounds like a great solution though! - shall I send a separate PR adding this information to the README, and also modify the Hakyll build so that it automatically writes to `docs` instead of `_site`?

**Comment by paf31** [comment]
I think the `generator` branch is dead at this point. Last time, I think I just used the `generator` directory in `master` and copied the contents of `_site` manually. It's still not ideal though.

**Comment by paf31** [comment]
Also, since this is an organization site, not a project site, the `docs` approach doesn't actually work 😞

**Comment by hdgarrood** [comment]
What counts as a project site?

**Comment by paf31** [comment]
The user or organization site is the main one for the user or organization (e.g. this one in our case). Everything else is a project site and lives in `gh-pages` or a `docs` folder in some repo under the organization.

**Comment by paf31** [comment]
Look under Settings for this repo, and you'll see this message underneath "Source":

> User pages must be built from the master branch.

**Comment by hdgarrood** [comment]
Ahh, right - in that case presumably we can convert this site into a project site by renaming the repo then?

**Comment by paf31** [comment]
Yes, I think so, although I'm not sure if project pages will continue to be hosted on `purescript.org/<project-name>` if we do that. Not that we use that feature right now, but it might be nice to create project pages for the core libraries one day.

I'm also not sure if the `CNAME` files will continue to work for subdomains like Try PureScript.

We could try it and see though.

**Comment by hdgarrood** [comment]
Actually never mind, I think what we have currently in `master` works. I'll send a new PR and then we can delete the `generator` branch if you agree.

**Pull request closed without merging**
