### PR TITLE
Update copyright

### PR DESCRIPTION
**Pull request by may17**
The copyright should be the current year or 2017 - 2019

### CODE REVIEW

**Comment by hdgarrood** [comment]
Would you mind changing it to say 2017-2019? Thanks!

**Comment by garyb** [comment]
I'm going to be super picky, and say can we make it `2017–2019`? :smile: (en dash rather than hyphen)

**Comment by may17** [comment]
Done like @garyb suggested 😄

**Comment by hdgarrood** [comment]
Thank you!

**Pull request merged**
