### PR TITLE
"Getting Started" for Download and Learn

### PR DESCRIPTION
**Pull request by damncabbage**
This is something that's bugged me for a while, but a confused visitor in IRC just showed how pertinent it is to fix it.

The Frankly Rather Good "[getting started](http://www.purescript.org/learn/getting-started/)" guide that @paf31 wrote is a bit buried on the Learn page. With first-timers likely clicking either Learn **or** Download, I've opted to add a consistent banner for both that'll hopefully guide them towards the post.

I've also changed the blockquote styling, as I was finding the italics harder to read, and said styling is front-and-centre here. (Bonus: it might be an [accessibilty improvement](http://ux.stackexchange.com/a/62752).)

screen shot 2016-03-19 at 6 14 58 pm

(Please, err, feel free to critique the quoted text.)

### CODE REVIEW

**Comment by beckyconning** [comment]
:+1:

**Comment by soupi** [comment]
Perhaps the "...walk-through __of__ setting up..." should be "...walk-through __to__ setting up..."?

Also, I think we could even go further and put a link the the getting started page on the front page right next to __try__. Maybe something like this?
screen shot 2016-03-19 at 12 15 26 pm

**Comment by damncabbage** [comment]
Thanks. :)

"a step-by-step walk-through of setting up and using PureScript."
  =>
"a step-by-step primer to setting up and using PureScript."

I went back and forth on adding it to the big callout, but I think it's in enough places with the two likely entry-points where people might click to get started with a local copy. (… I do admit to having complete banner-blindness with regards to the existing "try" link. :cold_sweat:)

**Comment by paf31** [comment]
:+1: Thanks!

**Pull request merged**
