### PR TITLE
Generate RSS and Atom feeds

### LINKED ISSUE #69: RSS Feed

### PR DESCRIPTION
**Pull request by paf31**
Resolves #69

### CODE REVIEW

**Comment by garyb** [comment]
Do we want to include whole articles in the feed? Might it be better to truncate them/just provide a description?

**Comment by paf31** [comment]
I'm thinking specifically of sites like Planet Haskell which typically show a whole post, but we could probably trim it down by putting the first paragraph in the description.

**Comment by garyb** [comment]
I don't mind either way actually, as a site "owner" it's nice to have people see your stuff the way it's supposed to look, but as a consumer it's pretty convenient to read the whole thing in your reader :wink:

**Comment by AppShipIt** [comment]
Whichever way looks right in a reader. I use Instapaper but feedly or Safari Reader might provide good baselines.

**Pull request closed without merging**
