### PR TITLE
Favicon!

### LINKED ISSUE #21: favicon?
I could probably have a go at making one out of the logo.

### PR DESCRIPTION
**Pull request by AppShipIt**
Fix #21.

32 and 256 px icons rendered from AI file using Autodesk Graphic with canvas cropped to 120 px and bundled using Icon Composer for Xcode:

1. 32 px instead of 16 for HiDPI cf. h5bp/html5-boilerplate#1285. Rendered at 49 px then cropped and overexposed using Acorn.
2. 256 px for app icons; untested. Rendered at 259 px then cropped using Acorn.

Let me know if the PNGs should be uploaded to the logo repo.

### CODE REVIEW

**Comment by paf31** [comment]
Thanks! Please feel free to make a PR on the `logo` repo, if you like.

**Comment by paf31** [comment]
Actually, now I see this, I wonder if it would look better inverted with the background made transparent. What do you think?

**Comment by AppShipIt** [comment]
I wondered too. It's an easy enough fix. Your call!

**Comment by paf31** [comment]
Yeah, let's try it then.

**Comment by garyb** [comment]
I had trouble getting the icon to look right at small sizes too, I got annoyed at a certain point and gave up but then forgot to come back to it... I think either this way or on a transparent background had issues, but it's worth trying again, sure.

**Comment by AppShipIt** [comment]
Yeah I took several different tacts but ended up having to use vector tools. I also made a 16-px version for the `ico` but the browser used it instead of 32 on my retina so I left it out.

**Pull request merged**
