### PR TITLE
Add chocolatey package.

### PR DESCRIPTION
**Pull request by alexchandel**
[The package](https://chocolatey.org/packages/purescript).

### CODE REVIEW

**Comment by paf31** [comment]
Looks good. How does the package work? Does it include actual executables, or does it download from the releases page?

**Comment by garyb** [comment]
From purescript/purescript#954:

> I created a v0.6.9.3 package for [chocolatey here](https://chocolatey.org/packages/purescript). It's actually pretty simple to do (if not well-documented). The package's file hierarchy is shown [here](https://chocolatey.org/packages/purescript); when creating a package, a [nuspec](https://gist.github.com/alexchandel/488c99fcbae79eb3cc26) is just added in the root folder, next to the `tools` directory.

**Comment by paf31** [comment]
I guess I'd prefer to have the package download the binaries from GitHub, but if that's not possible, no worries, let's merge.

**Comment by alexchandel** [comment]
I used the binaries from the GitHub release page. @paf31 I think downloading/extracting is a little more complicated in Chocolatey, and it requires some PowerShell scripts (which horrifies me).

Building the Chocolatey package isn't that hard though; it's just untarring the README & LICENSE in `win64.tar.gz` into `purescript/tools`, untarring the exes into `purescript/tools/bin/`, copying the Nuspec into `purescript/`, and calling `choco pack` and `choco push` from within `purescript/`.

**Pull request merged**
